version: "3"
services:
  api-dev:
    image: node:erbium
    environment:
      - PORT=${API_PORT}
      - DB_SERVICE=${DB_SERVICE}
      - DB_USER=${MONGODB_USER}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - DB_PORT=${MONGODB_PORT}
    volumes:
      - ../api:/usr/src/api
      - api-node-cache:/usr/src/api/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - swu_blue
    working_dir: /usr/src/api
    depends_on:
      - database
    command: npm run start-dev

  frontend-dev:
    image: node:erbium
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../frontend:/usr/src/frontend
      - frontend-node-cache:/usr/src/frontend/node_modules
    working_dir: /usr/src/frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - swu_blue
    command: npm run start-dev

  api:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    environment:
      - PORT=${API_PORT}
      - DB_SERVICE=${DB_SERVICE}
      - DB_USER=${MONGODB_USER}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - DB_PORT=${MONGODB_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - swu_blue
    depends_on:
      - database

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    environment:
      - WEB_HOST_NAME=${WEB_HOST_NAME}
      - WEB_HOST_PORT=${WEB_HOST_PORT}
    ports:
      - ${WEB_HOST_PORT}:${WEB_HOST_PORT}
    networks:
      - swu_blue

  database:
    image: registry.access.redhat.com/rhscl/mongodb-36-rhel7
    environment:
      - MONGODB_ADMIN_PASSWORD=${MONGODB_ADMIN_PASSWORD}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - database-data:/data/db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - swu_blue

  keycloak:
    image: jboss/keycloak:7.0.0
    environment:
      DB_VENDOR: ${KEYCLOAK_DB_VENDOR}
      DB_ADDR: ${KEYCLOAK_DB_ADDR}
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_LOGLEVEL: ${KEYCLOAK_LOGLEVEL}
      ROOT_LOGLEVEL: ${KEYCLOAK_ROOT_LOGLEVEL}
      KEYCLOAK_IMPORT: ${KEYCLOAK_IMPORT}
    volumes:
      - ../docker/keycloak/config:/tmp
    ports:
      - 8180:8080
    depends_on:
      - keycloak-db
    networks:
      - swu_blue

  keycloak-db:
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest
    environment:
      POSTGRESQL_USER: ${KEYCLOAK_DB_USER}
      POSTGRESQL_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRESQL_DATABASE: ${KEYCLOAK_DB_NAME}
    volumes:
      - keycloak-db-data:/var/lib/pgsql/data
    networks:
      - swu_blue

networks:
  swu_blue:

volumes:
  keycloak-db-data:
  database-data:
  api-node-cache:
  frontend-node-cache:
